databases:
  - name: qqx-db
    region: frankfurt
    databaseName: qqx
    user: qqx_admin
    plan: free

services:
  # Der Express API Service
  - type: web
    name: qqx-backend
    env: node
    region: frankfurt
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: qqx-db
          property: connectionString
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: CLERK_SECRET_KEY
        sync: false
